### ISSUE TITLE
Crashes and repetitive uploads

### ISSUE THREAD

**Issue by yunrr** [sboesen/remotely-sync#94] opened 2024-01-07 17:38 UTC
### What happened?

When uploading large files (50-100MB) to OneDrive through remote sync, Obsidian becomes extremely laggy and frequently crashes. It may be because after a crash, the entire large file needs to be re-uploaded (personal speculation). There will be multiple instances of uploading the same large file. Typically, it will repeat the upload process 5-10 times.

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.4.34

### Version of Obsidian

1.4.16（114）

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by kadisonm** [comment] 2024-01-08 00:53
I've noticed it trying to run multiple syncs at a time as well. I'll have a look into it.

**Comment by sboesen** [comment] 2024-01-08 02:28
Seems like a duplicate of #42 - please reopen if you disagree. Large files are not handled gracefully by Remotely Save and options for potentially fixing them (lately appearing limited) are discussed in the issue comments there.

**Closed by sboesen** 2024-01-08 02:28 UTC
Labels: bug

**Comment by yunrr** [comment] 2024-01-09 07:02
Thank you for your timely response! It appears to be a previously raised issue.

Indeed, disabling encryption improves the stability of transferring large files. However, when transferring extremely large files (such as a 1.9GB video), there is a phenomenon of upload failure without any error message, and the upload process continues. In a two-hour period, the uploaded traffic was 13GB. However, this doesn't have much impact on the usage.
